/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/krgyoahDT2R
 */
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Textarea } from "~/components/ui/textarea"
import { Button } from "~/components/ui/button"
import PageLayout from "~/components/layout/PageLayout"
import ThinPageTitle from "~/components/header/thin-page-title"

export default function ContactUsPage() {
  return (
    <PageLayout>
    <ThinPageTitle title="Contact Us" description="We'll get back to you as soon as possible." />
      
    <div className="container mx-auto max-w-[768px] w-full space-y-8">
      <section className="py-12 md:py-16">
        
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="first-name">First name</Label>
              <Input id="first-name" placeholder="Enter your first name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="last-name">Last name</Label>
              <Input id="last-name" placeholder="Enter your last name" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="phone">Phone (optional)</Label>
            <Input id="phone" placeholder="Enter your phone number" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
          </div>
          <Button>Send message</Button>
        </div>
      </section>
    </div>
    </PageLayout>
  )
}
