/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rrbUHPgS7bM
 */
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "~/components/ui/select"
import { Button } from "~/components/ui/button"
import ThinPageTitle from "~/components/header/thin-page-title"
import { UrlShortenerForm } from "~/components/url_shortener"

export default function MyLinksPage() {
  return (
    <>
    <ThinPageTitle title="My Links" description="View and manage your shortened URLs." />
    <div className="">
      <UrlShortenerForm />
      <div className="flex flex-col items-center justify-center h-full">
        
        <div className="w-full max-w-md p-4">
          <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-4">Your Shortened URLs</h2>
          <div className="space-y-4">
            <div className="flex items-center justify-between bg-gray-100 dark:bg-gray-700 p-4 rounded-md">
              <div>
                <p className="text-sm text-gray-900 dark:text-white mb-1">stub.by/3rFg4</p>
                <p className="text-xs text-gray-500">Clicked 24 times</p>
              </div>
              <Button size="sm" variant="ghost">
                Copy
              </Button>
            </div>
            <div className="flex items-center justify-between bg-gray-100 dark:bg-gray-700 p-4 rounded-md">
              <div>
                <p className="text-sm text-gray-900 dark:text-white mb-1">stub.by/7tYh1</p>
                <p className="text-xs text-gray-500">Clicked 67 times</p>
              </div>
              <Button size="sm" variant="ghost">
                Copy
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
    </>
  )
}
